# Generated by Django 3.2.8 on 2021-10-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_moderated', models.BooleanField(default=False)),
            ],
        ),
    ]
