# Generated by Django 3.2.8 on 2021-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
